#!/usr/bin/env bash
set -euo pipefail

# One-click Tor + Privoxy installer for Ubuntu/Debian
# Creates a backup of existing /etc/privoxy/config and writes a safe forwarding rule.

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this script with sudo or as root: sudo $0"
  exit 2
fi

echo "=== Tor + Privoxy installer (Ubuntu / Debian) ==="
echo

# Update package list
apt-get update

# Install required packages non-interactively
DEBIAN_FRONTEND=noninteractive apt-get install -y tor privoxy curl

# Ensure tor service is enabled
systemctl enable --now tor

# Backup existing privoxy config
PRIVOXY_CFG="/etc/privoxy/config"
BACKUP_DIR="/etc/privoxy/backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
if [ -f "$PRIVOXY_CFG" ]; then
  echo "Backing up existing privoxy config to $BACKUP_DIR/"
  cp -a "$PRIVOXY_CFG" "$BACKUP_DIR/config"
fi

# Write new privoxy config (keeps existing config header/comments where possible)
cat > "$PRIVOXY_CFG" <<'PRIVCFG'
# Privoxy main config - autogenerated by install-tor-privoxy.sh
# Listen on localhost only (HTTP proxy)
listen-address  127.0.0.1:8118

# Allow localhost access (default is restrictive; this ensures localhost can use it)
permit-access  127.0.0.1

# Forward all HTTP requests through Tor's SOCKS5 proxy and force hostname resolution through SOCKS
# forward-socks5t  /               127.0.0.1:9050 .
# The dot at the end is required by privoxy syntax

forward-socks5t   /               127.0.0.1:9050 .
# Optional: enable remote toggle (commented out by default)
enable-remote-http-toggle  1

# Keep other default behaviors; minimal config for HTTP->SOCKS bridging.
PRIVCFG

# Set proper permissions
chown root:root "$PRIVOXY_CFG"
chmod 644 "$PRIVOXY_CFG"

# Restart privoxy
systemctl enable --now privoxy
systemctl restart privoxy || true

echo
echo "=== Verification checks ==="

# Check tor and privoxy listening ports
echo "- Checking listening sockets (should see tor on 9050 and privoxy on 8118):"
ss -ltnp | grep -E ":(9050|8118)" || true

# Quick service status
echo
echo "- Tor service status:"
systemctl is-active --quiet tor && echo "tor: active" || echo "tor: NOT ACTIVE (check /var/log/syslog or journalctl -u tor)"
echo "- Privoxy service status:"
systemctl is-active --quiet privoxy && echo "privoxy: active" || echo "privoxy: NOT ACTIVE (check /var/log/syslog or journalctl -u privoxy)"

# Optional curl tests (do not perform onion fetch by default)
echo
echo "You can test connectivity with these commands (run them yourself):"
echo "1) Check Privoxy HTTP proxy is responding (HTTP status may vary):"
echo "   curl -I -x http://127.0.0.1:8118 http://example.com || true"
echo
echo "2) Verify Tor SOCKS is listening:"
echo "   ss -ltnp | grep 9050 || true"
echo
echo "3) (Advanced) Use Tor directly with curl via SOCKS5 to fetch clearnet check:"
echo "   curl --socks5-hostname 127.0.0.1:9050 https://check.torproject.org/ || true"
echo
echo "4) To test an .onion site using Privoxy (if you know a working onion):"
echo "   curl -x http://127.0.0.1:8118 http://exampleonionaddress.onion/ || true"
echo
echo "=== Final notes ==="
echo "- Configure your browser's HTTP proxy to: 127.0.0.1 port 8118"
echo "- For Firefox: Preferences → General → Network Settings → Manual proxy configuration → HTTP Proxy 127.0.0.1 Port 8118 (you may check 'Use this proxy for all protocols')"
echo "- For Chrome: either use system proxy or start with --proxy-server='http://127.0.0.1:8118'"
echo
echo "If you want to uninstall later, run the following commands:"
echo "  sudo systemctl stop privoxy tor"
echo "  sudo apt-get remove --purge -y privoxy tor"
echo "  sudo rm -f $PRIVOXY_CFG"
echo "  sudo cp -a $BACKUP_DIR/config $PRIVOXY_CFG  # to restore old config (if available)"
echo
echo "Script completed."
